### ISSUE TITLE
gradle failed

### ISSUE THREAD

**Issue by fukemy** [KiBa1215/MP3Recorder#1]
hi, i got this problem:
```
A problem occurred configuring project ':audio_record'.
> java.lang.NullPointerException (no error message)


```
can u help? Thanks

**Comment by KiBa1215** [comment]
Hi, 
you can simply upgrade the gradle plugin version and try again. This is the project created years ago, maybe with too low gradle version.
ps: as I remember the ndk version I used was r10e. FYI.

Thanks!
